### ISSUE TITLE
Footer section

### ISSUE THREAD

**Issue by Rki2711** [Rki2711/Hackthon#2]
Align the footer content with equal distance/space between them

**Comment by ngoctruc16** [comment]
Hi! Can you assign me this issue?

**Comment by Rki2711** [comment]
Try to solve this problem if as soon as possible.

**Comment by ngoctruc16** [comment]
Can I push the post directly or create another forked branch?

**Comment by Rki2711** [comment]
yes

**Comment by ngoctruc16** [comment]
I create a fork branch and I upload the footer edits. Please check to see if it is suitable for you.
